version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./server/data:/data/db
    restart: unless-stopped
    networks:
      - jotrack

  server:
    image: server:latest
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - jotrack


  # client:
  #   image: client
  #   build:
  #     context: ./client
  #     dockerfile: ./Dockerfile
  #   container_name: client 
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  #   networks:
  #     - jotrack

networks:
  jotrack:
    driver: bridge
