version: '3.8'

services:
  postgresql-jotrack:
    image: postgres:16-alpine
    container_name: postgresql-jotrack
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql-jotrack
#    volumes:
#      - ./server/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - jotrack

  server:
    image: server:1.0
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgresql://admin:password@postgresql-jotrack:5432/postgresql-jotrack
    ports:
      - "8000:8000"
    depends_on:
      - postgresql-jotrack
    networks:
      - jotrack

  client:
    image: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - jotrack

networks:
  jotrack:
    driver: bridge
